### ISSUE TITLE
CSS needs to be updated

### ISSUE THREAD

**Issue by kannangr21** [kannangr21/HTMLFormatter#1]
The existing css (styling) is very basic, participate in the hacktoberfest by contributing to this repo too.
Update the style of the site. Visit the link for existing style. Follow the `readme.md` file for running the server in the local machine.
https://html-formatter-flask.herokuapp.com/

**Comment by rwitesh** [comment]
Can you please assign me this issue @kannangr21

**Comment by kannangr21** [comment]
> Can you please assign me this issue @kannangr21

Without assigning the work to you, work on it and send a pull request, If interested.

**Comment by attreyee-muk** [comment]
Can I also work on this issue?

**Comment by kannangr21** [comment]
@a-muk Yeah sure!
